### ISSUE TITLE
Updates to Ubuntu Installation Wiki and CMake

### ISSUE THREAD

**Issue by WHSnyder** [seedhartha/reone#1]
For the wiki, Reone requires Boost 1.68 or greater, which is not available in the default apt repository on Ubuntu 18.04, so one must add the lastest version [manually](https://stackoverflow.com/questions/55678779/getting-boost-1-68-working-on-ubuntu-18-04)  

For CMake, I ran into linker errors until I made the Boost::system dependency explicit in the CMakeLists: <pre>find_package(Boost REQUIRED COMPONENTS <b>system</b> filesystem program_options) </pre>   <pre> target_link_libraries(revan PRIVATE ${Boost_FILESYSTEM_LIBRARY} ${Boost_PROGRAM_OPTIONS_LIBRARY} <b> ${Boost_SYSTEM_LIBRARY} </b> GLEW::GLEW ${OPENGL_LIBRARIES} ${MAD_LIBRARY}) </pre>

**Comment by seedhartha** [comment]
Added Boost.System to dependencies. How did you come up with that version number (1.68), though? I could target the lower version, if practical.

**Comment by WHSnyder** [comment]
I kept getting missing header errors, boost/asio/thread_pool.h was one I can remember off the top of my head.  Earlier versions than 1.68 might have it, but 1.68 was the only one I found when googling around for a bit.  I haven't used boost all that much, so I could be wrong...
