### ISSUE TITLE
Request: Error log

### ISSUE THREAD

**Issue by DarthParametric** [seedhartha/reone#10]
I did a brief test with K1 after seeing your post on Reddit. It seems that it works on a clean install, but it fails to run on a modded install. It would be useful to have some sort of detailed error log output to trace the root cause.

**Comment by seedhartha** [comment]
You can enable debug output (and module selection) using this command line parameter: --debug=[1-3]

**Comment by DarthParametric** [comment]
Hrm, it doesn't keep the console open, so it doesn't help much in this particular instance, since it closes within about a second. But after repeated attempts I have determined that it doesn't accept MP3s in streamwaves or a loose VIS in the Override.

**Comment by seedhartha** [comment]
I see. To redirect log to a file, a pipe could be used from the command line: reone --debug=2 > reone.log
Could you attach the log file, please?

**Comment by DarthParametric** [comment]
The log only has an error about not finding the TSL exe:

`DEBUG Path not found: "F:\Star Wars Knights of the Old Republic\K1" swkotor2.exe`

But by running it from a command window rather than the exe or a shortcut, I get:

`ERROR Resource type not found by extension: vis`

**Comment by seedhartha** [comment]
This is indeed a bug, triggered by a loose VIS file. I'll fix it. Thanks for the information!

**Comment by DarthParametric** [comment]
You're also lacking an entry in util.cpp for MP3, which was my previous error. I fixed it in my case by renaming them to WAV and adding the fake header, but lots of older mods make use of MP3s. The primary example is TSLRCM.

**Comment by seedhartha** [comment]
Added normal MP3 support and fixed handling of files with unknown extensions. Could you check? Release version 0.7.1.

**Comment by DarthParametric** [comment]
Yeah that works, although it seems like it is ignoring loose custom TGAs in the Override, complaining that it can't find the TPC of the same filename.

**Comment by seedhartha** [comment]
Yeah, modding support has a long way to go 🙂 I'm closing this issue as of now, since it doesn't crash anymore, but will keep your findings in mind. Thanks!
