### ISSUE TITLE
Request: Developer's Guide

### ISSUE THREAD

**Issue by uwadmin12** [seedhartha/reone#11]
IMO the project could really benefit from a developer's guide. Particularly regarding architectural details, and how subsystems interact with each other.

I'm sure people who worked on the xereos project would have little difficulty getting started developing a new feature, but us filthy casuals could really use a developer's guide.

And yes, I'm hoping to contribute and complete the road map :)

**Comment by seedhartha** [comment]
Good idea. I'll add more architectural info to the [Development](https://github.com/seedhartha/reone/wiki/Development) page.

**Comment by seedhartha** [comment]
Take  a look, please. Is this what you had in mind? 🙂

**Comment by uwadmin12** [comment]
Yes, appreciate the update! 
I'll see how far I get 👍
