### ISSUE TITLE
Segmentation Fault for ACTION 197 1

### ISSUE THREAD

**Issue by uwadmin12** [seedhartha/reone#12]
I was playing around with the scripting system and added spawn script execution for creatures to see the list of instructions in the log:

```c++
void Area::loadCreatures(const GffStruct &git) {
    for (auto &gffs : git.getList("Creature List")) {
        shared_ptr<Creature> creature(_objectFactory->newCreature());
        creature->load(gffs);
        landObject(*creature);
        creature->setSynchronize(true);
        add(creature);

        // missing functions below were implemented following 
        // PlaceableBlueprint's example
        string script;
        if (creature->blueprint().getScript(CreatureBlueprint::ScriptType::Spawn, script)) {
            runScript(script, creature->id(), kObjectInvalid, -1);
        }
    }
}
```

## Expected Behaviour

I get to see the list of instructions being executed.

## Actual Behaviour

All of the spawn scripts results in segmentation fault. And the last known script command is `ACTION 197 1`. 

Do you know the human-readable interpretation of this command?

## Sample Logs

For example, k_def_spawn01 has this issue:

```
DEBUG Resources: load k_def_spawn01.ncs
DEBUG Script: k_def_spawn01
DEBUG Script: JSR 00000015
DEBUG Script: RSADDx
...
DEBUG Script: MOVESP
DEBUG Script: RSADDx
DEBUG Script: CPTOPSP
DEBUG Script: ACTION 197 1
Segmentation fault
```

Complete logs for different spawn scripts:

1. https://pastebin.com/W9ViFi7f
2. https://pastebin.com/wph6RDnd
3. https://pastebin.com/n3hYbDT4

**Comment by seedhartha** [comment]
"ACTION 197 1" means calling engine routine 197 with a single argument. Routine 197 is GetWaypointByTag (you may find the number in nwscript.nss).

This segfault is probably due to GetWaypointByTag accessing module's _area member which is not initialized at this point.

**Comment by uwadmin12** [comment]
Thanks for the info. Indeed, when I move the spawn script execution all the way up to Game::loadModule, there is no longer segmentation fault. Unfortunately, I didn't get any interesting information out of the set of instructions from a hostile spawn, other than a bunch of generic listeners for stuff like "GEN_I_WAS_ATTACKED", "GEN_I_SEE_AN_ENEMY", etc.

One interesting thing I noticed during testing is whenever a dialogue ends in combat initiation, the program aborted with message "Assertion failed: count == 1, file C:\reone\src\script\execution.cpp, line 529", and the combat-initiation instructions are recorded:

https://pastebin.com/QqEZbEbq

This was the 3 dark jedi encounter on kas22_ab, and you can see instruction `ChangeToStandardFaction -> void` 3 times (to hostile faction), and after which there are combat-related commands like `GetLastHostileTarget -> 1`.

**Comment by seedhartha** [comment]
Interesting. This is a not a bug per se, but an invalid assumption on my part (that CPDOWNBP and CPTOPBP are always executed with _count_ parameter 1).  I'll remove those assertions and see what happends.

**Comment by uwadmin12** [comment]
(Off topic but ...) quick question about animation: 

So I know a list of Animation objects are loaded from `Resource` into a `Model`, and each `SpatialObject` is associated with a `ModelSceneNode` (which is a tree of <model-animations> that is representative of skeletal animations? Sorry I never quite understood animation in any games ...)

By calling `SpatialObject::animate` with a string like `g_animTalkBody`, the animation rendered in-game will be replaced by g_animTalkBody after `ModelSceneNode::doUpdate`.

Is there a comprehensive reference for `g_anim*` strings?

I could help to record and test those.

**Comment by uwadmin12** [comment]
Tested the latest scripting change with another hostile dialog (the czerka guards in kas22_ab), and got this weird error:

```
DEBUG Script: JSR 000012c8
DEBUG Script: RSADDx
DEBUG Script: CONSTx 0
DEBUG Script: ACTION 721 1
DEBUG Script: GetLastHostileTarget -> 1
DEBUG Script: CPDOWNBP
DEBUG Script: MOVESP
DEBUG Script: CPTOPBP
DEBUG Script: DESTRUCT
DEBUG Script: ACTION 732 1
DEBUG Script: received variable type: '1'; expected variable type '4'!              <-- 1 is Int and 4 is Object
ERROR Script: invalid argument variable type
```

So in K1's nwscript.nss, the function declaration is `int GetIsDebilitated(object oCreature = OBJECT_SELF);`, which is consistent with `add("GetIsDebilitated", Int, { Object });` defined in `routine_kotor.cpp`.

Any ideas how this happened?

**Comment by seedhartha** [comment]
There was a bug in CPDOWNBP, which copied from an incorrect place. Dialog with the Czerka guards works now.

**Comment by uwadmin12** [comment]
Confirmed, thanks!!
