### ISSUE TITLE
Setup CI tests to avoid crossplatform issues

### ISSUE THREAD

**Issue by neuromancer** [seedhartha/reone#2]
It would be nice to setup some CI tests to detect crossplaform issues when compiling and running this neat reimplementation. It is worth to mention that [travis](https://travis-ci.com) is free for open-source repositories and has support for Linux and OSX.

**Comment by DrMcCoy** [comment]
Feel free to take the xoreos Travis CI config files as a template. If something there is unclear, I'll try to answer that as well.

Personally, I found Travis CI, while nice for providing free service to FLOSS projects, relatively annoying to handle. Their build VMs are often pretty out of date and break relatively often in mysterous ways, needing me to hunt around to see which things they silently changed.

There's also some arcane things they do you don't have access to. For example, I've set Travis CI up to automatically submit builds pushed into a certain branch to Coverity Scan (which is pretty neat!), but that's only partially documented. I don't know where/how exactly they check for Coverity Scan rate limits, that part of the script is completely hidden to me, so I can't change a few things it does slightly not ideal.

**Comment by seedhartha** [comment]
Integrated Travis CI as requested.
