### ISSUE TITLE
Invalid shader/shader compilation error on mesa intel

### ISSUE THREAD

**Issue by Ziemas** [seedhartha/reone#24]
`ERROR Shader 4 compilation failed: 0:126(31): error: sampler arrays indexed with non-constant expressions are forbidden in GLSL 1.30 and later`

Stemming from:
https://github.com/seedhartha/reone/blob/a6aa70e2e7603d0c9442300fc066b55c02d924e3/src/render/shaders.cpp#L265

Dynamically indexing into sampler arrays is not allowed, I guess some implementations are lax about this but mesa does not allow it.

Not sure what the best way to work around this is.

**Comment by seedhartha** [comment]
Fixed by 03ac08c85a343fec0edacd7ff9a1ee3c6faaa3f0. Thanks for reporting it!

**Comment by Ziemas** [comment]
:+1:
