### ISSUE TITLE
Missing GNU licence

### ISSUE THREAD

**Issue by daniel-brenot** [seedhartha/reone#28]
Please include a LICENCE file with this project. You state in the source you are under the GNU public licence, but have not attached a copy, which violates the licence

**Comment by DrMcCoy** [comment]
https://github.com/seedhartha/reone/blob/master/COPYING ?

**Comment by seedhartha** [comment]
^ This. COPYING is explicitly [mentioned](http://www.gnu.org/licenses/gpl-howto.en.html) on their website.

**Comment by daniel-brenot** [comment]
Sorry, I was expecting a LICENCE file so I missed it.
