### ISSUE TITLE
Please explain the reone-tools commands better

### ISSUE THREAD

**Issue by daniel-brenot** [seedhartha/reone#29]
I can't seem to understand how to use the commands. I followed the instructions and ran:
`
./reone/reone-tools --game "D:\\Program Files (x86)\\Steam\\steamapps\\common\\swkotor" --extract "sounds.bif" --dest ../raw-assets/sounds`

but I keep getting the error "ERROR Input file does not exist: sounds.bif"

What am I missing, and can the documentation be extended to explain what the input file is for the bif file?

**Comment by seedhartha** [comment]
Yeah, tools are not exactly user-friendly at the moment. You're got it right though, except for the fact that all paths must be absolute. I'll make sure to mention it in the docs.

**Comment by seedhartha** [comment]
Added a note regarding absolute paths to the wiki.
