### ISSUE TITLE
Potential contribution to the project

### ISSUE THREAD

**Issue by lachjames** [seedhartha/reone#3]
Hi :)

This is a great project, and I'm really glad that someone has started this! I've been working on a similar project in Unity for a few months now, and I've made some progress. I've been looking through your project and I have a few things to add/suggest:

**General Resource Management**
I would strongly suggest that you consider changing the implementation of the resource management in the following ways:
 - Create C++ structs representing all the different types (e.g. .dlg, .utc, .utd, ...) which contain all the fields used by the respective formats.
 - Write code that takes a gff file and deserializes it into a struct (and vice versa). This code can be generic.

The official BioWare documentation helps here, but it's not perfect as it was written for Neverwinter Nights and there are changes for the Odyssey engine (and, I imagine, for KOTOR specifically as well). Nailing these differences did take some trial and error, but I can help with this as I have actually already implemented this in C#. I'd be happy to share what I've learned with you, as well as my code. The code I have written for C# uses reflection for generalization and simplicity, so it won't be a straight port. It remains to be seen whether the reflection adds too much overhead (my feeling is that it doesn't, at least on modern hardware). However, it's undoubtedly possible to implement this in C++ (in the worst case, just hard-coding a serializer would be possible, though tedious).

The advantages of this approach mainly stem from being able to use properties of e.g. creatures in code by specifically referencing the values (rather than doing a lookup on a GFF object by name):
 - Greater IDE support
 - Compile-time type checking
 - In general, it just avoids a lot of bugs that come from getting stuff at runtime

**Rendering Subsystem**
I think it's great that you've implemented a custom rendering system. No comments here.

**Audio Subsystem**
Adding surround sound support here would be awesome.

**GUI Subsystem**
I have more comments on the GUI below.

**Async Jobs Subsystem**
One thing to notice is that the game's scripts (as in, the NSS scripts) make extensive use of the DelayCommand engine routine; be careful as it's unclear how much of this is written asynchronously vs synchronously, and mistakes here could lead to game scripts not working properly. My intuition is that the game likely runs almost completely synchronously, given the hardware it ran on.

**Collision detection**
Using the original walk-meshes is one approach, but I would suggest that it would be better to generate them on the fly using the game. The original walk meshes are well-known to be quite bad, and computers these days can easily generate better walk meshes on the fly. This might break some cutscenes, but that's fixable (and honestly, some cutscenes are already broken due to the existing walk-meshes anyway...).

**Multiplayer**
Be careful here, as the engine routines support both GetFirstPC and GetNextPC, and since the game is intended to be single-player these would (quite reasonably) have been expected to be identical according to the original developers and might have been used interchangeably in places.

Onto the "to-do" list:

**Original UI**
I'm of two minds with this. On one hand, the original UI is fairly outdated these days, and a modern revamp would not go amiss. On the other hand, it is actually possible to use the original UI assets (I think most people in the KOTOR community underestimate how much of the UI is actually done through scripting and GUI assets). My personal feeling is that it would be easier in the short term to implement a custom UI system and then, later on, use the original GUI assets to hook into this UI system if users want that "old school feel".

**Scripting system**
The scripting subsystem has three components:
 - Reading the NCS bytecode
 - Running the NCS bytecode in a "virtual machine"-like environment
 - Implementing all the >700 engine routines that the NSS scripts rely on

I have implemented the NCS virtual machine in C#, and would be happy to share this with you. I've implemented other assembly simulators before (namely a MIPS simulator, which I plan to make open source fairly soon). I'd be more than happy to share this code with you.

The first component is implementing a disassembler for NCS bytecode - however, this is trivialized by the fact that xoreos-tools includes a disassembler. Since their code is open source, you could use their implementation - in my experience, it's great.

There are some tricky parts to the NCS virtual machine (namely with vectors and structs), but it's easier to run the code than to disassemble it for sure as the NCS compiler strips away most of the vector and struct logic (but not all of it - some commands work on vectors, e.g. the ADDVV command, which adds two vectors).

The most difficult part of the scripting system is implementing all of the >700 engine routines. Some of them are trivial (e.g. d4, which returns a random 4-sided dice roll), and some are quite complex and require entire subsystems (e.g. the object system). I've made some steps towards implementing this and would be happy to discuss it with you.

**Dialog/cutscenes**
I've also implemented a dialog system (several times, in fact, in both Python for a dialog editor, and C#/Unity for a dialog player). It's quite straightforward and I'd be happy to share my code. The difficulties with more complex cutscenes are composed of movies and stunts; stunts will require some work but I discuss how movies can be implemented relatively easily below.

**Party management**
Like the UI, most of this is actually done via scripting and the engine routine calls are quite simple. This would not be difficult to implement.

**Combat**
The enemy AI is implemented in NSS/NCS script, which simplifies the combat a lot as only the subsystems have to be implemented (and these are quite straightforward). However, if there is one part of this project that should be made "modular", it's the combat system, as this would allow you/me/others to implement our own combat systems.

**Game Saves**
Game saves work by saving GFF files (in fact, a lot of it is really just saving edited copies of the files that come with the game). It's more complex than that, of course, but implement a GFF writer and you're halfway there.

**Environmental sounds**
Don't really have any comments here.

**Movies**
This might seem difficult (getting the movies to play was initially the most daunting problem for me) - however, fortunately the hard work has already been done by the ffmpeg community and KOTOR's .bik files are readable by ffmpeg. My suggestion for this is to do one of the following:
 - On installation, convert all the .bik files to .mp4; from there, playing the videos is straightforward
 - At runtime, stream the .bik files through ffmpeg in-memory and play the resulting video feed

Either method works; I'd suggest implementing the first one for now as it's straightforward and, further down the track, maybe giving streaming a try. You can actually do this with a one-liner on linux (in the "movies" directory, and requiring ffmpeg installed of course):

    for i in *.bik; do ffmpeg -i "$i" "${i%.*}.mp4"; done

**Custom game modes**
As you no doubt know, the Aurora engine uses the NSS scripting language, which already has compilers written for it (and decompilers, one of which I have written and published on my GitHub page).

Some other things I'd like to add:

**Mod support**
This is very important (especially for KOTOR 2, where TSLRCM is basically mandatory). 

**Rendering engine**
Using a custom rendering engine is great, and I understand if you wish to keep going down that path. However, I'd suggest considering moving your implementation into Unity (I'd be happy to combine your implementation with mine and collaborate with you on this). This is for several reasons:
 - I already have a lot of C# code, e.g. a dialog and scripting system. There is also another project, which creates a graphics pipeline for importing assets into Unity (https://github.com/rwc4301/KotOR-Unity) - it has some problems with animations (I've fixed some of them and plan to submit them to the original repo).
 - Unity's rendering system is quite good, and supports some awesome features. You could, for example, use the built-in post-processing and ray tracing features to significantly improve the look of the game "almost for free".
 - Most of your code could be ported to C# with relatively little trouble, because C# is (unsurprisingly) a C-based language.

**Summary**
This is an awesome project, and I can't wait to see what you do next. I'd be extremely excited to work with you on this. If you'd like to contact me on Discord, please feel free to add me. If you're on the DeadlyStream discord, you should be able to add me as I'm on it too; if not, please let me know and I can enable all incoming friend requests (I leave it off by default as otherwise spam can get through). My username is lachjames#6269.

**Comment by DrMcCoy** [comment]
@lachjames, I know you're aware of xoreos-tools, but are you aware of xoreos proper? :P

A lot of the things you speak of xoreos already does and since @seedhartha did contribute to xoreos, he should be aware of that. While he can't directly move over code (well, code he didn't write himself) unless he wants to "poison" his MIT-licensed codebase with GPLv3+ code, he's free to read the general gist of what xoreos does and reimplement it here.

> On installation, convert all the .bik files to .mp4; from there, playing the videos is straightforward

That's a terrible idea. Back in the day, something like that was done with NWN on Linux (by each user, BioWare simply disabled video playback altogether on Linux), because RAD Game Tools didn't provide a Linux player at that time. The results were okay-ish, but not great. Bink is geared towards videos found in games, including 3d renders and drawn graphics, most modern video codecs are focused on real-world footage. This increases the artifacts you're going to see because of transcoding even more.

Really, there's no reason reone can't just link against the LGPLv2 ffmpeg library and use that one to play videos. Simple. The only downside is adding such a big and unwieldy dependency.

That's the reason I took a different path in xoreos: I basically took the ffmpeg Bink code, cleaned it up considerably according to my own standards and added it to xoreos. That also helped me in understanding how Bink works in the first place. Of course, that only works because the licenses are compatible, you can't do that with an MIT-licensed project like that.

**Comment by neuromancer** [comment]
I don't know if @seedhartha is aware, but there is also this KotOR reimplmentation in Javascript/Node that could be useful to speed-up the development of reone: https://github.com/KobaltBlu/KotOR.js

**Comment by lachjames** [comment]
@DrMcCoy pleasant surprise to see you :)

I didn't see that the codebase here is MIT licensed. As you know, my code uses the same license as xoreos (by design), so if this project were to use my code it would have to convert to a similar license (which I encourage anyway, so xoreos code can be used).

I think "terrible idea" is a bit strong (you wound me, @DrMcCoy) - in my experience, there isn't a significant fidelity loss after the conversion if a good configuration is used. However, I of course agree that your solution is more ideal, although it takes more work, and I wanted to suggest an easy fix as it was listed as the last option on the todo list. I initially did the mp4 conversion myself to try out upscaling the videos using Gigapixel (which works great), so reading .bik just wasn't an option. But hey, if a better solution's already implemented, that's great!

Of course, I am aware of xoreos, and I think it's awesome. However, as you know better than anyone it will be significantly more difficult to recreate a generic game engine framework such as Aurora/Odyssey rather than just implementing it for a single game (or, in this case, two very similar games - KOTOR and TSL). I think a concerted, community-wide effort to recreate the Odyssey engine for KotOR and TSL would be quite fruitful (especially if an existing game engine like Unity was used to speed up development). To that end, I've made a Discord server (see below).

@neuromancer I think I saw that node.js project a while back but must have forgotten about it - it looks quite cool. Great to see so many people interested in re-implementing the game engine for KotOR.

I'm currently aware of at least five different projects for recreating the KotOR engine to some extent. For that reason, I've created a Discord server for us all to use (linked below). Anyone's welcome, and doubly so for people working on these sorts of projects.

Discord server: https://discord.gg/yGyqvb

**Comment by seedhartha** [comment]
@lachjames First of all, thank you for such a thorough analysis (I'm taking notes here) :)

It is indeed good to see so much people interested in the game, and I'm all for collaboration in this effort of creating an open source version of the Odyssey engine.

Regarding the five existing projects: frankly, I only ever heard about xoreos, and my reasons to start a new project where:
- being able to focus on KotOR and TSL (which are the only games xoreos targets that I'm interested in);
- having an unlimited amount of freedom in design choices regarding architecture, features, libraries, etc.

To that end, NOT using C#, Unreal Engine, Unity, OGRE or OSG was a deliberate choice and I'm highly unlikely to switch from using C++ and custom rendering engine at this point.

**Comment by lachjames** [comment]
@seedhartha Thanks for taking a look at what I wrote - I suspected you'd say as much regarding the rendering engine but I thought I'd give it a shot anyway :)

No reason there can't be both a pure C++ implementation that's true to the original and a Unity C# implementation that utilises modern hardware/features. I'm sure we can learn from each other too.

Thanks for joining the Discord server too :)

Can't wait to see where this project leads; we will watch your career with great interest :) please let me know if there's ever anything I can do to help!

**Comment by neuromancer** [comment]
Just found [this](https://github.com/BBBrassil/SithCodec) browsing GitHub. I don't know if it is useful for decoding audio tracks or it was already re-implemented here.

**Comment by seedhartha** [comment]
> Just found [this](https://github.com/BBBrassil/SithCodec) browsing GitHub. I don't know if it is useful for decoding audio tracks or it was already re-implemented here.

Audio decoding is already implemented. Not exactly a rocket science, how Bioware "encrypted" their audio 🙂
