### ISSUE TITLE
Dependencies inaccurate on Ubuntu 21.10 (20.04+)

### ISSUE THREAD

**Issue by sam4b** [seedhartha/reone#42]
Instructions are currently (to compile from source): `sudo apt install libboost-all-dev libsdl2-dev libglew-dev libopenal-dev libmad0-dev libavcodec-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev libwxgtk3.0-dev`

libwxgtk3.0-dev was changed to libwxgtk3.0-gtk3-dev in 20.04 so naturally this apt command fails. You can solve this with a quick Google, but I think its better to change the documentation.

Source:  https://askubuntu.com/questions/1241217/package-libwxgtk3-0-dev-has-no-installation-candidate-on-ubuntu-20-04

I'm not aware of any way to fork & submit a PR to the wiki so I thought an issue would be the best idea.

**Comment by seedhartha** [comment]
Hey. I changed the doc, thanks for bringing this up.
