### ISSUE TITLE
Automatically generated classes for all KOTOR GFF formats

### ISSUE THREAD

**Issue by lachjames** [seedhartha/reone#5]
Hi :)

It's been great to see the significant progress made on this project in the last few weeks.

I have been working today on a tools that automatically generates classes for each of the GFF file types used by the Odyssey engine for K1/TSL. I have used the code from [this repo](https://github.com/rwc4301/KotOR-Unity) for reading GFF files, and written code which takes these files and automatically generates C# classes. I have attached preliminary versions of these files to this issue, generated for KOTOR 1 (TSL adds more fields I think, so this would have to be re-run for TSL's game files - however, the analysis runs in seconds so this is not a problem).

My original plan was to generate these by analyzing the PDF documentation for the Aurora engine, but I quickly concluded this to be a less than optimal solution for several reasons, including:
 - Errors in PDF parsing (the libraries I tried were pretty good, but not perfect).
 - Missing/new variables for KOTOR/TSL which are not in the Aurora documentation (which was written for NWN).

So I decided it would be better to generate the classes directly from the GFF objects, and wrote some code to do that. It works pretty well, and I think it would not be difficult to modify the code to output valid C++ instead of C#. I could do this (with some help from you regarding variable types and how you would want to structure the code), or alternatively it would only take about 5 minutes of "find-replace in all files in folder" actions to mostly convert it from C# to C++ (essentially changing variable types and some syntax).

Again, please find the files attached here.

One caveat: when the GFF files are saved by the Odyssey engine, sometimes new GFF fields are added; these are currently not included in the class definitions because they are generated from the original game files. One of my next objectives is to add save game analysis which finds these extra variables, but this will take some further analysis.

Thanks again for this great project :)

[Classes.zip](https://github.com/seedhartha/reone/files/5073212/Classes.zip)

**Comment by seedhartha** [comment]
Thanks for the hard work 🙂 I can definetely see the merit in separation of the blueprint code. As for the C# to C++ conversion, I can do it, no problem.
