### ISSUE TITLE
 Error starting Ubuntu arm64

### ISSUE THREAD

**Issue by ArtemS2** [seedhartha/reone#54]
I tried to launch Star Wars: Knights of the Old Republic steam version, but the game immediately crashed.
[reone.log](https://github.com/seedhartha/reone/files/13849336/reone.log)

**Comment by ArtemS2** [comment]
Help me please ! Can anything be done about this?

**Comment by seedhartha** [comment]
> maximum output vertices (12) exceeds GL_MAX_GEOMETRY_OUTPUT_VERTICES

What GPU do you have? Looks like it doesn't support some engine features.

**Comment by ArtemS2** [comment]
@seedhartha  My GPU: Arm Mali-G610 MP4. I'm trying to run on Orange pi 5b

**Comment by seedhartha** [comment]
Interesting, this GPU supports up to OpenGL ES 3.2, reone requires OpenGL 3.3 Core. I may add support for this in the future, but for now this is out of scope. Also keep in mind that the game is far from playable right now.
