### ISSUE TITLE
What's the difference between the Reone project and the Xoreos project?

### ISSUE THREAD

**Issue by gnarlin** [seedhartha/reone#7]
What's the difference between the Reone project and the Xoreos project? Can you merge the work done or at least co-operate or share the work and tools that have already been created?

**Comment by seedhartha** [comment]
For starters, I'm aware of xoreos and had comitted to it in the past. I use it alot as a reference, but this project is created entirely from scratch.

Merging would defeat the purpose for which I started reone in the first place, which is:
1. Being able to focus exclusively on KotOR and TSL
2. Having a creative freedom to experiment with different algorithms, patterns, libraries, etc.
3. Fun of building the entire thing, delving into graphics, audio, networking, scripting, etc.

Regarding KotOR and TSL, xoreos currently has slightly more implemented in terms of gameplay + it has support for movies. reone has multiplayer, it is more performant and has an arguably leaner codebase.

The way I see it, reone has a much better chance of making KotOR and TSL completable in a reasonable amount of time.

**Comment by itoshkov** [comment]
I think this should go in the README.

**Comment by seedhartha** [comment]
Added Similar Projects section to the readme file.

**Comment by gnarlin** [comment]
Well, I just wanted to wish you good luck. We're all counting on you!
